# ===== Build stage =====
FROM afrotek/nest-base:latest AS builder
WORKDIR /app/services/user-service
COPY services/user-service ./
RUN npm install --legacy-peer-deps
RUN npm run build

# ===== Runtime stage =====
FROM node:20-alpine AS runtime
ENV NODE_ENV=production
WORKDIR /app

COPY package*.json ./
COPY libs/common/package*.json libs/common/
COPY services/user-service/package*.json services/user-service/

RUN npm config --global set registry https://registry.npmmirror.com
RUN npm install --omit=dev --legacy-peer-deps --workspaces

COPY --from=builder /app/services/user-service/dist ./dist
EXPOSE 3004
CMD ["node", "dist/main.js"]
